### ISSUE TITLE
ox-rst adds section numbers on the headings

### ISSUE THREAD

**Issue by joonro** [masayuko/ox-rst#12]
I installed Org mode 8.3beta and tried ox-rst. Strangely, it added section numbers automatically to headings. For example, when I export the following

```
*** Testing
**** Introduction
***** Introduction
****** Introduction
:PROPERTIES:
:BEAMER_OPT: allowframebreaks
:END:

- Introduction
```

I get 

```rst
    Testing
    =======
    
        :Author: Joon Ro
    
    .. contents::
    1 Introduction
    --------------
    
    1.1 Introduction
    ~~~~~~~~~~~~~~~~
    
    1.1.1 Introduction
    ^^^^^^^^^^^^^^^^^^
    
    - Introduction
```

I have a org link with `elisp:(org-rst-export-to-rst nil t)`, inside the `Testing` subtree which I use to export the subtree.

**Comment by masayuko** [comment]
Hi.
Please add a following line in your org file.
#+OPTIONS: num:nil

See also http://orgmode.org/manual/Export-settings.html

**Comment by joonro** [comment]
I think I was mistaken. Thank you so much for quick reply.
