### ISSUE TITLE
#+BEGIN_EXPORT rst - don't work

### ISSUE THREAD

**Issue by lloydhuang** [masayuko/ox-rst#28]
Dear Masayuko 

The ox-rst is work well for me. Thank you.

late week I was git pull, then find out  #+BEGIN_EXPORT rst don't work.

(sample)
#+BEGIN_EXPORT rst
.. class:: alert
#+END_EXPORT

(output)
.. EXPORT::

    \.. lass:: alert

version commit 7b6095c53211978c73e1d686cd2d672cf28eb4c3

Best Regards
Lloyd

**Comment by masayuko** [comment]
Which version of org-mode do you use?
Upstream has changed export block syntax at Org 9.0.

Old syntax was:

#+BEGIN_RST
.. class:: alert
#+END_RST

It work fine for me with new syntax.

**Comment by lloydhuang** [comment]
My Emacs org version is 8.3.3

old syntax 
#+BEGIN_RST
.. class:: alert
#+END_RST

outout as below
.. RST::

    \.. lass:: alert

BTW, I used #+BEGIN_QUOTE for workaround. Unfortunately, it also have HTML URL link problem. like below.

#+ATTR_RST: :directive raw :title html
#+BEGIN_QUOTE
<embed src="http:///www.youtube.com/xxxx/"></embed>
#+END_QUOTE

.. raw:: html

    <embed src="`http:///www.youtube.com/xxxx/ <http:///www.youtube.com/xxxx/>`_"></embed>

BRs
Lloyd

**Comment by lloydhuang** [comment]
update org-mode to version 9.0.3

Then, It work. Thank you.

BRs
Lloyd
