### ISSUE TITLE
Can ox-rst export arbitrary fields?

### ISSUE THREAD

**Issue by beetleb** [masayuko/ox-rst#31]
rst supports arbitrary fields (date, author, etc are examples). However, I do not see any way to add arbitrary fields through org mode. It supports some (date, author, etc). But what if I want a field called "Blah"?

My use case is that I'm using ox-rst to export org docs to rst for use in a static site generator. Each post should have a Tags field (think blog posts). Right now I have to hand edit the .rst file that ox-rst produces, which is a pain.

**Comment by masayuko** [comment]
The exporting of 'in-buffer settings' in Org mode need a special kind of handling.
In past days, I made ox-nikola (https://github.com/masayuko/ox-nikola) for Nikola blog posts.
So we should make ox-pelican derived from ox-rst for pelican blog posts.

**Comment by masayuko** [comment]
There is another solution.

Please try this:

#+BEGIN_EXPORT rst
:tags: tag1 tag2 tag3
#+END_EXPORT

**Comment by beetleb** [comment]
Hi,

The EXPORT method solves the problem. Thanks!

As for making an ox-pelican, that may be cool, provided we add a lot more Pelican related features. Otherwise it may be a bit of an overkill...
