### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by strow** [masayuko/ox-rst#7]
Hi again,

By the way, ox-rst is great, really working really well except for this one issue.  

It appears to me that ox-rst will only properly create rst tables if there are lines around all elements.

ie
  
  |  top  | right |
  | here | there |

will not be converted properly, but

  |-------+--------|
  |  top  | right  |
  |-------+--------|
  | here | there |
  |-------+--------|

*will* be converted properly.

For example, the following will also not be converted properly

  |-------+--------|
  |  top  | right  |
  | here | there |
  |-------+--------|

Larrabee

**Comment by masayuko** [comment]
Hi, strow.

Please try this commit.
