### ISSUE TITLE
Symbol's function definition is void: org-export-custom-protocol-maybe

### ISSUE THREAD

**Issue by sinewalker** [masayuko/ox-rst#8]
I'm actually using ox-nikola to try convert an orgmode file to .rst.  One file worked, but one with links to the web failed with this error.

I traced it back to ox-rst. It seems ox-rst is calling this function in converting org links, but the function is not a part of ox.el (at least, not in the latest orgmode package from the orgmode ELPA repo? (20150202)).  Which version of org is this written against?

I have tried using the latest org package, and also the builtin orgmode from emacs 24.4, but get the same error.  

I know that ox has been a bit of a moving target this past year or so, wondering if something has changed, yet again, affecting your code?  Pretty interested to find a fix because this alternative looks a lot more flexible than the plugin for Nikola.

**Comment by masayuko** [comment]
Hi, sinewalker.
Thank you for trying this one.

org-export-custom-protocol-maybe is not defined with org-mode 8.2.10 (20150202) or org-mode 8.2.x (emacs 24.4.1).

I'm using 8.3beta (the master repo at git://orgmode.org/org-mode.git) that have the function.

**Comment by sinewalker** [comment]
Thanks Masayuko :-)

I've been putting off switching to the bleeding edge of Orgmode, but I think I've just found a reason to!

**Comment by sinewalker** [comment]
closed - sorry left it open so long...
