### ISSUE TITLE
Wrong type argument: sequencep, :input-buffer

### ISSUE THREAD

**Issue by yi-tang** [masayuko/ox-rst#9]
Hi,

When I try to use `ox-rst` to convert a org file to rst format, it throw this error:

`Wrong type argument: sequencep, :input-buffer`

A minimal example is 

```
* Headline 
A sentence 
```

If the org file has a table, I will get this error: 

`org-at-table.el-p: Symbol's function definition is void: org-table-begin`

I am using org-mode 8.3beta, and ox-rst is installed from melpa.

**Comment by masayuko** [comment]
Hi. Thank you for letting me know.
Please try recent commits.

**Comment by yi-tang** [comment]
Hi, The recent commits solve the problem, thanks for your quick fix.
